# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title NLopt Call Example from Rcpp
#'
#' @description A simple example for for NLopt integration for Rcpp, using an example from the
#' NLopt tutorial.
#'
#' @details This function illustrates use of \pkg{NLopt} from R without requiring linking.
#' It relies on the set of exported functions the \pkg{nloptr} R package provides directly
#' (and also instantiates) using a method described in \emph{Writing R Extensions}. There
#' is also a C++ interface to \pkg{NLopt} but it requires linking making use from another
#' R package a little more involved as presence and location of the \pkg{NLopt} library
#' may need to be checked (though using \pkg{pkgconf} can help).
#'
#' @param method A string defaulting to \sQuote{MMA} (also allowing \sQuote{COBYLA})
#' which selects the algorithm use.
#' @param verbose A boolean toggle defaulting to \sQuote{false}
#'
#' @return A numeric vector with two elements
#'
#' @seealso \url{https://nlopt.readthedocs.io/en/latest/NLopt_Tutorial/}
#'
#' @examples
#' testConstrainedProblem("MMA", TRUE)
testConstrainedProblem <- function(method = "MMA", verbose = FALSE) {
    .Call(`_RcppNLoptExample_testConstrainedProblem`, method, verbose)
}

#' Helper function to access the NLopt version as an integer vector.
#'
#' @title NLopt Version as Vector
#' @return A list with an integer vector with three elements for major, minor
#' and patch release, classed as \code{package_version} and \code{numeric_version}.
#' @examples
#' nloptVersion()
nloptVersion <- function() {
    .Call(`_RcppNLoptExample_nloptVersion`)
}

