# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A simple example for for NLopt integration for Rcpp,
#' using an example from the NLopt tutorial.
#'
#' @title NLopt Call Example from Rcpp
#' @param method A string defaulting to \sQuote{MMA} (also allowing \sQuote{COBYLA})
#' which selects the algorithm use.
#' @param verbose A boolean toggle defaulting to \sQuote{false}
#' @return A numeric vector with two elements
#' @seealso \url{https://nlopt.readthedocs.io/en/latest/NLopt_Tutorial/}
#' @examples
#' testConstrainedProblem("MMA", TRUE)
testConstrainedProblem <- function(method = "MMA", verbose = FALSE) {
    .Call(`_RcppNLoptExample_testConstrainedProblem`, method, verbose)
}

